service: sls-twilio-again

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    # replace these env variables with your twilio account values
    TWILIO_ACCOUNT_SID: ${file(./env.json):TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${file(./env.json):TWILIO_AUTH_TOKEN}
    TWILIO_PHONE_NUMBER: ${file(./env.json):TWILIO_PHONE_NUMBER}

functions:
  sendText:
    handler: handler.sendText
    events:
      - http:
          path: api/sendText
          method: post
          integration: lambda
          cors: true
